### ISSUE TITLE
java.lang.OutOfMemoryError when building the extension. Docs needed?

### ISSUE THREAD

**Issue by valo** [google/end-to-end#367]
I am trying to build chrome extension, but I get:

```bash
[~/workspace/end-to-end]$ ./do.sh build_extension                                                                                                                                                                     All dependencies met.
Using previous template build. Run ./do.sh clean if you want to rebuild the templates.
Building End-To-End extension to build/extension
Compiling JS files...
.java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:2367)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:480)
	at java.lang.StringBuilder.append(StringBuilder.java:191)
	at java.lang.StringBuilder.append(StringBuilder.java:184)
	at java.lang.StringBuilder.append(StringBuilder.java:72)
	at com.google.common.io.CharStreams.copy(CharStreams.java:70)
	at com.google.common.io.CharStreams.toStringBuilder(CharStreams.java:99)
	at com.google.common.io.CharStreams.toString(CharStreams.java:86)
	at com.google.common.io.CharSource.read(CharSource.java:148)
	at com.google.common.io.Files.toString(Files.java:264)
	at com.google.javascript.jscomp.SourceFile$OnDisk.getCode(SourceFile.java:482)
	at com.google.javascript.jscomp.CompilerInput.getCode(CompilerInput.java:291)
	at com.google.javascript.jscomp.CompilerInput.regenerateDependencyInfoIfNecessary(CompilerInput.java:233)
	at com.google.javascript.jscomp.CompilerInput.getProvides(CompilerInput.java:168)
	at com.google.javascript.jscomp.Compiler.hoistExterns(Compiler.java:1450)
	at com.google.javascript.jscomp.Compiler.parseInputs(Compiler.java:1357)
	at com.google.javascript.jscomp.Compiler.parse(Compiler.java:783)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:744)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:95)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:656)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:653)
	at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:700)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
```

In order to fix this I did:

```bash
[~/workspace/end-to-end]$ export _JAVA_OPTIONS="-Xms512m -Xmx1024m"
```

Is this something worth mentioning in the `README` or in a page of the wiki?

**Comment by koto** [comment]
We could just add that to the ./do.sh script. Send a PR, please!

**Comment by Ricky54326** [comment]
See #369  - saw this had not been done yet and ran into the same error.

**Comment by valo** [comment]
I tried to reproduce the error a few days ago and surprisingly it worked that time, so I didn't prepare a PR. Glad that I am not the only one getting this error :)

**Comment by Ricky54326** [comment]
The PR was just merged as well so this problem should be resolved for everyone :) can be closed whenever.
