### ISSUE TITLE
No valid key blocks found. ed25519 public key

### ISSUE THREAD

**Issue by HLFH** [google/end-to-end#388]
Hi,

I built End-to-End extension on OS X 10.11.4 with Chrome with [the needed tools](https://github.com/google/end-to-end/wiki/Build-instructions).
I'm using it on Chrome 50.0.2661.94 (64-bit).
[mypubkey.txt](https://github.com/google/end-to-end/files/246670/mypubkey.txt)

But I got the issue: No valid key blocks found.
![capture d ecran 2016-05-03 a 12 21 35](https://cloud.githubusercontent.com/assets/2359059/14980547/a79c8b90-1129-11e6-967d-fe4b890aa73a.png)

It seems to be a ed25519 public key. I followed the first part of [this tutorial](http://www.gniibe.org/memo/software/gpg/keygen-25519.html).

What should I do? Is this a real issue?

JsUnit Tests:

```
Unit Test of e2e.otr.pubkey/ [FAILED]
127.0.0.1:8000/src/javascript/crypto/e2e/otr/pubkey_test.html
3 of 3 tests run in 8ms.
2 passed, 1 failed.
3 ms/test. 44 files loaded.
ERROR in testConstructor
Function passed to assertThrows caught a JsUnitException (usually from an assert or call to fail()). If this is expected, use assertThrowsJsUnitException instead.
> (unknown)
> Object.goog.testing.asserts.raiseException at http://127.0.0.1:8000/javascript/closure/testing/asserts.js:1251:11
> assertThrows at http://127.0.0.1:8000/javascript/closure/testing/asserts.js:285:28
> testConstructor at http://127.0.0.1:8000/src/javascript/crypto/e2e/otr/pubkey_test.html:60:3
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:851:21
> goog.testing.TestCase.safeRunTest_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:801:8
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:877:19
> goog.testing.TestCase.runNextTest_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:791:8
> anonymous at .&lt;anonymous&gt; (http://127.0.0.1:8000/javascript/closure/testing/testcase.js:757:10)
> new goog.Promise at http://127.0.0.1:8000/javascript/closure/promise/promise.js:164:16
> goog.testing.TestCase.runTestsReturningPromise at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:755:10
> goog.testing.TestRunner.execute at http://127.0.0.1:8000/javascript/closure/testing/testrunner.js:262:19

Run individually »
 
Unit Test of e2e.otr.session/ [FAILED]
127.0.0.1:8000/src/javascript/crypto/e2e/otr/session_test.html
3 of 3 tests run in 10ms.
1 passed, 2 failed.
3 ms/test. 91 files loaded.
ERROR in testConstructor
Function passed to assertThrows caught a JsUnitException (usually from an assert or call to fail()). If this is expected, use assertThrowsJsUnitException instead.
> (unknown)
> Object.goog.testing.asserts.raiseException at http://127.0.0.1:8000/javascript/closure/testing/asserts.js:1251:11
> assertThrows at http://127.0.0.1:8000/javascript/closure/testing/asserts.js:285:28
> testConstructor at http://127.0.0.1:8000/src/javascript/crypto/e2e/otr/session_test.html:42:3
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:851:21
> goog.testing.TestCase.safeRunTest_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:801:8
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:877:19
> goog.testing.TestCase.runNextTest_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:791:8
> anonymous at .&lt;anonymous&gt; (http://127.0.0.1:8000/javascript/closure/testing/testcase.js:757:10)
> new goog.Promise at http://127.0.0.1:8000/javascript/closure/promise/promise.js:164:16
> goog.testing.TestCase.runTestsReturningPromise at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:755:10
> goog.testing.TestRunner.execute at http://127.0.0.1:8000/javascript/closure/testing/testrunner.js:262:19

ERROR in testUpdateAuthState
Function passed to assertThrows caught a JsUnitException (usually from an assert or call to fail()). If this is expected, use assertThrowsJsUnitException instead.
> (unknown)
> Object.goog.testing.asserts.raiseException at http://127.0.0.1:8000/javascript/closure/testing/asserts.js:1251:11
> assertThrows at http://127.0.0.1:8000/javascript/closure/testing/asserts.js:285:28
> testUpdateAuthState at http://127.0.0.1:8000/src/javascript/crypto/e2e/otr/session_test.html:50:3
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:851:21
> goog.testing.TestCase.safeRunTest_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:801:8
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:877:19
> goog.testing.TestCase.runNextTest_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:791:8
> goog.testing.TestCase.finishTestInvocation_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:949:10
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:877:19
> goog.testing.TestCase.safeTearDown_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:816:8
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:877:19
> goog.testing.TestCase.safeRunTest_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:801:8
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:877:19
> goog.testing.TestCase.runNextTest_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:791:8
> goog.testing.TestCase.finishTestInvocation_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:949:10
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:877:19
> goog.testing.TestCase.safeTearDown_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:816:8
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:884:15
> goog.testing.TestCase.safeRunTest_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:801:8
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:877:19
> goog.testing.TestCase.runNextTest_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:791:8
> anonymous at .&lt;anonymous&gt; (http://127.0.0.1:8000/javascript/closure/testing/testcase.js:757:10)
> new goog.Promise at http://127.0.0.1:8000/javascript/closure/promise/promise.js:164:16
> goog.testing.TestCase.runTestsReturningPromise at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:755:10
> goog.testing.TestRunner.execute at http://127.0.0.1:8000/javascript/closure/testing/testrunner.js:262:19

Run individually »
 
Unit Test of e2e.otr.message.encoded/ [FAILED]
127.0.0.1:8000/src/javascript/crypto/e2e/otr/message/encoded_test.html
4 of 4 tests run in 12ms.
2 passed, 2 failed.
3 ms/test. 47 files loaded.
ERROR in testConstructor
Function passed to assertThrows caught a JsUnitException (usually from an assert or call to fail()). If this is expected, use assertThrowsJsUnitException instead.
> (unknown)
> Object.goog.testing.asserts.raiseException at http://127.0.0.1:8000/javascript/closure/testing/asserts.js:1251:11
> assertThrows at http://127.0.0.1:8000/javascript/closure/testing/asserts.js:285:28
> testConstructor at http://127.0.0.1:8000/src/javascript/crypto/e2e/otr/message/encoded_test.html:78:3
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:851:21
> goog.testing.TestCase.safeRunTest_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:801:8
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:877:19
> goog.testing.TestCase.runNextTest_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:791:8
> anonymous at .&lt;anonymous&gt; (http://127.0.0.1:8000/javascript/closure/testing/testcase.js:757:10)
> new goog.Promise at http://127.0.0.1:8000/javascript/closure/promise/promise.js:164:16
> goog.testing.TestCase.runTestsReturningPromise at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:755:10
> goog.testing.TestRunner.execute at http://127.0.0.1:8000/javascript/closure/testing/testrunner.js:262:19

ERROR in testPrepareSend
Function passed to assertThrows caught a JsUnitException (usually from an assert or call to fail()). If this is expected, use assertThrowsJsUnitException instead.
> (unknown)
> Object.goog.testing.asserts.raiseException at http://127.0.0.1:8000/javascript/closure/testing/asserts.js:1251:11
> assertThrows at http://127.0.0.1:8000/javascript/closure/testing/asserts.js:285:28
> testPrepareSend at http://127.0.0.1:8000/src/javascript/crypto/e2e/otr/message/encoded_test.html:105:3
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:851:21
> goog.testing.TestCase.safeRunTest_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:801:8
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:877:19
> goog.testing.TestCase.runNextTest_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:791:8
> goog.testing.TestCase.finishTestInvocation_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:949:10
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:877:19
> goog.testing.TestCase.safeTearDown_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:816:8
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:877:19
> goog.testing.TestCase.safeRunTest_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:801:8
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:877:19
> goog.testing.TestCase.runNextTest_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:791:8
> goog.testing.TestCase.finishTestInvocation_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:949:10
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:877:19
> goog.testing.TestCase.safeTearDown_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:816:8
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:884:15
> goog.testing.TestCase.safeRunTest_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:801:8
> goog.testing.TestCase.invokeTestFunction_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:877:19
> goog.testing.TestCase.runNextTest_ at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:791:8
> anonymous at .&lt;anonymous&gt; (http://127.0.0.1:8000/javascript/closure/testing/testcase.js:757:10)
> new goog.Promise at http://127.0.0.1:8000/javascript/closure/promise/promise.js:164:16
> goog.testing.TestCase.runTestsReturningPromise at http://127.0.0.1:8000/javascript/closure/testing/testcase.js:755:10
> goog.testing.TestRunner.execute at http://127.0.0.1:8000/javascript/closure/testing/testrunner.js:262:19

Run individually »
```

I'm using jdk-8u92-macosx-x64.dmg. Should I use a previous JDK version?

**Comment by sirdarckcat** [comment]
hi

we havent finished implementing support for ed25519 yet. we landed some patches last week but it's not all there yet.

**Comment by HLFH** [comment]
@sirdarckcat Ok thanks!

**Comment by sirdarckcat** [comment]
lets track this in https://github.com/google/end-to-end/issues/319
